# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Add all the games
Game.create(name: 'Scavenger Hunt', referee: 'Sam Ritter')
Game.create(name: 'Saltine Challenge', referee: 'Wisdom Omuya')
Game.create(name: 'Avalon', referee: 'Amalia Hawkins')
Game.create(name: 'Charades', referee: 'Kyle Erf')
Game.create(name: 'Uno', referee: 'Sam Helman')
Game.create(name: 'Poker', referee: 'Spencer Brody')
Game.create(name: 'Blackjack', referee: 'Matt Dannenberg')
Game.create(name: 'Apples to Apples', referee: 'Kyle Erf')
Game.create(name: 'Spoons', referee: 'Amalia Hawkins')
Game.create(name: 'Connect4', referee: 'Spencer Brody')
Game.create(name: 'Pool', referee: 'Wisdom Omuya')
Game.create(name: 'Basketball', referee: 'Amy Berman')
Game.create(name: 'Table Tennis', referee: 'Dave Storch')
Game.create(name: 'Set', referee: 'Amalia Hawkins')
Game.create(name: 'Bananagrams', referee: 'Dave Storch')
Game.create(name: 'Scattergories', referee: 'Sam Ritter')
Game.create(name: 'Boggle', referee: 'Sam Ritter')
Game.create(name: 'Taboo', referee: 'Sam Helman')
Game.create(name: 'Super Smash Brothers', referee: 'Phil Quiza')
Game.create(name: 'Jenga', referee: 'Matt Dannenberg')
Game.create(name: 'Operation', referee: 'Phil Quiza')
Game.create(name: 'Trivia', referee: 'Sam Helman')
Game.create(name: 'Hula Hoop Contest', referee: 'Amy Berman')

# Add all the players (=interns)
Player.create(fullname: 'Aaron Hammond', email: 'aaron.hammond@mongodb.com')
Player.create(fullname: 'Alex Grover', email: 'alex.grover@mongodb.com')
Player.create(fullname: 'Alex Kleinman', email: 'alex.kleinman@mongodb.com')
Player.create(fullname: 'Antonio Juliano', email: 'antonio.juliano@mongodb.com')
Player.create(fullname: 'Bill DeRose', email: 'bill.derose@mongodb.com')
Player.create(fullname: 'Cody Wilson', email: 'cody.wilson@mongodb.com')
Player.create(fullname: 'Esha Maharishi', email: 'esha.maharishi@mongodb.com')
Player.create(fullname: 'J Delaney', email: 'j.delaney@mongodb.com')
Player.create(fullname: 'Jao-ke Chin-Lee', email: 'jaoke.chinlee@mongodb.com')
Player.create(fullname: 'Jason Brooks', email: 'jason.brooks@mongodb.com')
Player.create(fullname: 'Jed Estep', email: 'jed.estep@mongodb.com')
Player.create(fullname: 'Judah Schvimer', email: 'judah.schvimer@mongodb.com')
Player.create(fullname: 'Kyle Suarez', email: 'kyle.suarez@mongodb.com')
Player.create(fullname: 'Maggie Cai', email: 'maggie.cai@mongodb.com')
Player.create(fullname: 'Maria van Keulen', email: 'maria.vankeulen@mongodb.com')
Player.create(fullname: 'Matt Cotter', email: 'matt.cotter@mongodb.com')
Player.create(fullname: 'Matthew Neubauer', email: 'matthew.neubauer@mongodb.com')
Player.create(fullname: 'Melissa OSullivan', email: 'melissa.osullivan@mongodb.com')
Player.create(fullname: 'Rahul Dhodapkar', email: 'rahul.dhodapkar@mongodb.com')
Player.create(fullname: 'Russel Kaplan', email: 'russel.kaplan@mongodb.com')
Player.create(fullname: 'Stuart Larsen', email: 'stuart.larsen@mongodb.com')
Player.create(fullname: 'Tianhao Zhang', email: 'tianhao.zhang@mongodb.com')
Player.create(fullname: 'Waley Chen', email: 'waley.chen@mongodb.com')
Player.create(fullname: 'Walter Menendez', email: 'walter.menendez@mongodb.com')
Player.create(fullname: 'Michael Rochlin', email: 'michael.rochlin@mongodb.com')
Player.create(fullname: 'Jason Hu', email: 'jason.hu@mongodb.com')
Player.create(fullname: 'Xander Masotto', email: 'xander.masotto@mongodb.com')
Player.create(fullname: 'Michael Whittaker', email: 'michael.whittaker@mongodb.com')
Player.create(fullname: 'Clare Paniccia', email: 'clare.paniccia@mongodb.com')
Player.create(fullname: 'Kenneth George', email: 'kenneth.george@mongodb.com')
Player.create(fullname: 'Eleanor Morris', email: 'eleanor.morris@mongodb.com')
Player.create(fullname: 'Jonathan Mason', email: 'jonathan.mason@mongodb.com')
Player.create(fullname: 'Josh Clapper', email: 'josh.clapper@mongodb.com')
Player.create(fullname: 'Jennifer Campbell', email: 'jennifer.campbell@mongodb.com')

# Link the players into teams
